-- Store written by physical-ai-safety-observability main @ 651525c (Alembic head 0003)
-- Generated by a one-off script from CameraIn payloads; used by the upgrade test.
BEGIN TRANSACTION;
CREATE TABLE alembic_version (
	version_num VARCHAR(32) NOT NULL, 
	CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);
INSERT INTO "alembic_version" VALUES('0003_camera_configs_and_settings');
CREATE TABLE camera_configs (
	camera_id TEXT NOT NULL, 
	enabled INTEGER DEFAULT '1' NOT NULL, 
	payload TEXT NOT NULL, 
	created_at TEXT NOT NULL, 
	updated_at TEXT NOT NULL, 
	PRIMARY KEY (camera_id)
);
INSERT INTO "camera_configs" VALUES('cell-a-entry',0,'{"name": "Cell A entry", "profile": "tapo", "host": "192.0.2.20", "port": 554, "username": "viewer", "stream_path": "", "stream_quality": "sub", "channel": 1, "rtsp_transport": "tcp", "location": "Bay 1", "zones": [{"zone_id": "gate", "type": "restricted", "polygon": [[0.1, 0.1], [0.9, 0.1], [0.9, 0.9], [0.1, 0.9]]}], "rules": ["PPE_MISSING", "RESTRICTED_ZONE_ENTRY"], "password_enc": "enc:v1:gAAAAABqx8tfgivldeGT4aPjHDz2T7KlsuImYEDfwNo2_KAgrWURL42BSnUHNuMz4IiFNPfK7Dq4ca-KR59GOuqwqMDAW5sOAw=="}','2026-10-08T16:57:03.224015+00:00','2026-10-08T16:57:03.224015+00:00');
INSERT INTO "camera_configs" VALUES('dock',0,'{"name": "Dock", "profile": "hikvision", "host": "192.0.2.21", "port": 8554, "username": "admin", "stream_path": "", "stream_quality": "main", "channel": 2, "rtsp_transport": "udp", "location": null, "zones": [], "rules": [], "password_enc": "enc:v1:gAAAAABqx8tf0xiiUTWtT8S5wNRg5cSlv0BjPaub9wRQ5g4_YgMOAAWHypkNvcAPzgVSJBsvVD7RXv83Ytuh7IWGOg067Et_HA=="}','2026-10-08T16:57:03.235918+00:00','2026-10-08T16:57:03.235918+00:00');
INSERT INTO "camera_configs" VALUES('protect-token',0,'{"name": "Protect token", "profile": "unifi_protect", "host": "192.0.2.30", "port": 7447, "username": "", "stream_path": "/AbCdEf123", "stream_quality": "main", "channel": 1, "rtsp_transport": "tcp", "location": null, "zones": [], "rules": [], "password_enc": ""}','2026-10-08T16:57:03.245313+00:00','2026-10-08T16:57:03.245313+00:00');
INSERT INTO "camera_configs" VALUES('open-stream',0,'{"name": "Open stream", "profile": "generic_rtsp", "host": "cam.example.test", "port": 554, "username": "", "stream_path": "/live/main", "stream_quality": "main", "channel": 1, "rtsp_transport": "tcp", "location": null, "zones": [], "rules": [], "password_enc": ""}','2026-10-08T16:57:03.253563+00:00','2026-10-08T16:57:03.253563+00:00');
INSERT INTO "camera_configs" VALUES('mjpeg-cam',0,'{"name": "MJPEG cam", "profile": "http_mjpeg", "host": "192.0.2.40", "port": 8080, "username": "", "stream_path": "", "stream_quality": "main", "channel": 1, "rtsp_transport": "tcp", "location": null, "zones": [], "rules": [], "password_enc": ""}','2026-10-08T16:57:03.262406+00:00','2026-10-08T16:57:03.262406+00:00');
INSERT INTO "camera_configs" VALUES('laptop-webcam',1,'{"name": "Laptop webcam", "profile": "browser_webrtc", "host": "", "port": null, "username": "", "stream_path": "", "stream_quality": "main", "channel": 1, "rtsp_transport": "tcp", "location": null, "zones": [], "rules": [], "password_enc": ""}','2026-10-08T16:57:03.271274+00:00','2026-10-08T16:57:03.271274+00:00');
INSERT INTO "camera_configs" VALUES('demo-feed',1,'{"name": "Demo feed", "profile": "synthetic", "host": "", "port": null, "username": "", "stream_path": "", "stream_quality": "main", "channel": 1, "rtsp_transport": "tcp", "location": null, "zones": [], "rules": [], "password_enc": ""}','2026-10-08T16:57:03.280548+00:00','2026-10-08T16:57:03.280548+00:00');
CREATE TABLE cameras (
	camera_id TEXT NOT NULL, 
	payload TEXT NOT NULL, 
	registered_at TEXT NOT NULL, 
	PRIMARY KEY (camera_id)
);
CREATE TABLE events (
	event_id TEXT NOT NULL, 
	camera_id TEXT NOT NULL, 
	rule_id TEXT NOT NULL, 
	severity TEXT NOT NULL, 
	timestamp TEXT NOT NULL, 
	incident_id TEXT, 
	payload TEXT NOT NULL, 
	PRIMARY KEY (event_id)
);
CREATE TABLE feedback (
	feedback_id TEXT NOT NULL, 
	camera_id TEXT NOT NULL, 
	frame_id TEXT NOT NULL, 
	message TEXT NOT NULL, 
	timestamp TEXT NOT NULL, 
	payload TEXT NOT NULL, 
	PRIMARY KEY (feedback_id)
);
CREATE TABLE incidents (
	incident_id TEXT NOT NULL, 
	camera_id TEXT NOT NULL, 
	rule_id TEXT NOT NULL, 
	grouping_severity TEXT NOT NULL, 
	opened_at TEXT NOT NULL, 
	updated_at TEXT NOT NULL, 
	payload TEXT NOT NULL, 
	PRIMARY KEY (incident_id)
);
CREATE TABLE settings (
	"key" TEXT NOT NULL, 
	value TEXT NOT NULL, 
	updated_at TEXT NOT NULL, 
	PRIMARY KEY ("key")
);
INSERT INTO "settings" VALUES('model','{"backend": "openai-compatible", "endpoint": "http://127.0.0.1:11434", "model": "gemma4", "think": false, "json_schema": false, "max_tokens": 512, "timeout_s": 60.0, "reasoning_parser": null, "label": "", "api_key_enc": "enc:v1:gAAAAABqx8tfsEUwqg7tIfbEjjbsjgOcn2WMrlw52rqDUJbyZFD-3V_JqDyQudL6d66sZTD-HEIpiBe3gdmY_p0HRN2khwnkkw=="}','2026-10-08T16:57:03.295781+00:00');
INSERT INTO "settings" VALUES('inference','{"interval_ms": 1500, "width": 640, "height": 360, "jpeg_quality": 80, "display_max_width": 1280, "post_batch": true, "post_feedback": true}','2026-10-08T16:57:03.305047+00:00');
CREATE INDEX idx_events_timestamp ON events (timestamp);
CREATE INDEX idx_events_incident ON events (incident_id);
CREATE INDEX idx_incidents_grouping ON incidents (camera_id, rule_id, grouping_severity, updated_at);
CREATE INDEX idx_feedback_timestamp ON feedback (timestamp);
COMMIT;
